#graphqls for graphql scema

type Query {

    #Company Queries
    getCompany(id: ID!): Company

    getAvailableAppointments(
        companyId: ID!
        date: String
    ): [Appointment]

    getAllAppointments(
        companyId: ID!
    ): [Appointment]

    getClients: [GetResponse]

    getCompanies: [Company]

    getMember(memberId: ID!): GetResponse

    getAllMembers: [GetResponse]

    #Appointment Queries
    getAppointment(id: ID!): Appointment
}

type Mutation {

    #Company Mutations
    createCompany(
        companyName: String!,
        ownerEmail: String!,
        ownerName: String!,
        ownerPassword: String!
    ): String

    editCompany(
        companyName: String,
        description: String,
        businessType: String
    ): String

    deleteCompany: String

    addMember(
        memberEmail: String!
        memberName: String!
        memberPassword: String!
    ): String

    deleteMember(
        memberId: ID!
    ): String

    #Appointment Mutations
    bookAppointment(
        appointmentId: ID!
    ): String

    createAppointment(
        from: String!,
        to: String!,
        clientId: ID,
        title: String,
        description: String,
        location: String,
    ): String

    editAppointment(
        id: ID!,
        from: String,
        to: String,
        clientId: ID,
        description: String,
        location: String,
        status: String
    ): String

    deleteAppointment(
        id: ID!
    ): String
}

type Company {
    id: ID
    name: String
    description: String
    businessType: String
    memberIds: [ID]
    ownerEmail: String
}

type Appointment {
    id: ID
    from: String
    to: String
    companyId: ID
    clientId: ID
    description: String
    location: String
    Status: String
}

type GetResponse {
    id: ID
    name: String
    created_at: String
    email: String
    role: String
    associatedCompany: ID
    subscribedCompanies: [ID]
}